version: '3.8'

services:
  app-debug:
    build: .
    ports:
      - "8000:8000"
      - "5678:5678"  # Debug port
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/eagle_bank
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - EVENT_BUS_URL=redis://redis:6379
      - KEYCLOAK_SERVER_URL=http://keycloak:8080
      - KEYCLOAK_REALM=eagle-bank
      - KEYCLOAK_CLIENT_ID=eagle-bank-api
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    depends_on:
      - db
      - redis
      - keycloak
    volumes:
      - .:/app
    command: python debug_main.py

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: eagle_bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    volumes:
      - keycloak_data:/opt/keycloak/data

volumes:
  postgres_data:
  redis_data:
  keycloak_data:
