apiVersion: apps/v1
kind: Deployment
metadata:
  name: eagle-bank-api
  labels:
    app: eagle-bank-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eagle-bank-api
  template:
    metadata:
      labels:
        app: eagle-bank-api
    spec:
      containers:
        - name: eagle-bank-api
          image: 123456789.dkr.ecr.us-west-2.amazonaws.com/eagle-bank-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: eagle-bank-secrets
                  key: database-url
            - name: REDIS_URL
              value: "redis://eagle-bank.cluster.cache.amazonaws.com:6379"
            - name: KEYCLOAK_SERVER_URL
              value: "https://keycloak.yourdomain.com" # External Keycloak
            - name: KEYCLOAK_REALM
              value: "eagle-bank"
            - name: KEYCLOAK_CLIENT_ID
              value: "eagle-bank-api"
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: eagle-bank-secrets
                  key: keycloak-client-secret
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: eagle-bank-secrets
                  key: jwt-secret-key
            - name: ENVIRONMENT
              value: "production"
            - name: DEBUG
              value: "false"
            - name: AWS_REGION
              value: "us-west-2"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: eagle-bank-api-service
spec:
  selector:
    app: eagle-bank-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eagle-bank-api-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:123456789:certificate/your-cert-id
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
spec:
  rules:
    - host: api.eaglebank.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eagle-bank-api-service
                port:
                  number: 80
